version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    container_name: repo-app
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
    links:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    container_name: repo-db
    environment:
      - POSTGRES_USER=repo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=repo_core
    ports:
      - "2345:5432"